# -*- coding: utf-8 -*-
"""Sales_volume_forecasting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xs1s7x-e5qY_y88Kg8Ox__OcEUBIWLM4
"""

!pip install streamlit
import streamlit as st

# Adjusting the page
st.set_page_config(
    page_title="Sales Volume Forecasting",
    page_icon="📈",
    layout='wide'
)

